import { ColorSemanticToken } from "../../types";

export const darkModeColorSemantic: Record<ColorSemanticToken, string> = {
  // Base
  baseBackground: "#09090B",
  baseForeground: "#FAFAFA",
  baseBorder: "#27272A",
  // Button
  buttonBackground: "#FAFAFA",
  buttonForeground: "#18181B",
  buttonBorder: "#27272A",
  buttonBackgroundHover: "#E4E4E7",
  buttonBackgroundActive: "#D4D4D8",
  buttonAccent: "#27272A",
  buttonAccentForeground: "#FAFAFA",
  // Button - Disabled
  buttonDisabledBackground: "#27272A",
  buttonDisabledForeground: "#71717A",
  // Button - Danger
  buttonDangerBackground: "#DC2626",
  buttonDangerForeground: "#FAFAFA",
  buttonDangerBorder: "#DC2626",
  buttonDangerBackgroundHover: "#EF4444",
  buttonDangerBackgroundActive: "#B91C1C",
  buttonDangerAccent: "#450A0A",
  buttonDangerAccentForeground: "#FCA5A5",
  buttonDangerDisabledBackground: "#450A0A",
  buttonDangerDisabledForeground: "#F87171",
  // Input
  inputBackground: "rgba(39, 39, 42, 0.3)",
  inputForeground: "#FAFAFA",
  inputBorder: "#27272A",
  inputBorderFocus: "#D4D4D8",
  inputRingFocus: "rgba(212, 212, 216, 0.2)",
  inputPlaceholder: "#71717A",
  inputBorderError: "#DC2626",
  inputRingError: "rgba(220, 38, 38, 0.4)",
  inputDisabledBackground: "#27272A",
  inputDisabledForeground: "#71717A",
  // Checkbox
  checkboxBackground: "transparent",
  checkboxForeground: "transparent",
  checkboxBorder: "#52525B",
  checkboxCheckedBackground: "#FAFAFA",
  checkboxCheckedForeground: "#18181B",
  checkboxCheckedBorder: "#FAFAFA",
  checkboxDisabledBackground: "#27272A",
  checkboxDisabledForeground: "#52525B",
  checkboxDisabledBorder: "#3F3F46",
  checkboxLabel: "#FAFAFA",
  checkboxLabelDisabled: "#71717A",
  // Radio
  radioBorder: "#52525B",
  radioBackground: "transparent",
  radioSelectedBorder: "#FAFAFA",
  radioSelectedDot: "#FAFAFA",
  radioDisabledBorder: "#3F3F46",
  radioDisabledBackground: "#27272A",
  radioDisabledDot: "#52525B",
  radioLabel: "#FAFAFA",
  radioLabelDisabled: "#71717A",
  // Switch
  switchTrack: "#3F3F46",
  switchTrackActive: "#FAFAFA",
  switchThumb: "#FAFAFA",
  switchThumbActive: "#18181B",
  switchTrackDisabled: "#27272A",
  switchThumbDisabled: "#52525B",
  switchLabel: "#FAFAFA",
  switchLabelDisabled: "#71717A",
};
