import { ColorSemanticToken } from "../../types";

export const lightModeColorSemantic: Record<ColorSemanticToken, string> = {
  // Base
  baseBackground: "#FFFFFF",
  baseForeground: "#09090B",
  baseBorder: "#E4E4E7",
  // Button
  buttonBackground: "#18181B",
  buttonForeground: "#FAFAFA",
  buttonBorder: "#E4E4E7",
  buttonBackgroundHover: "#27272A",
  buttonBackgroundActive: "#09090B",
  buttonAccent: "#F4F4F5",
  buttonAccentForeground: "#18181B",
  // Button - Disabled
  buttonDisabledBackground: "#F4F4F5",
  buttonDisabledForeground: "#A1A1AA",
  // Button - Danger
  buttonDangerBackground: "#DC2626",
  buttonDangerForeground: "#FAFAFA",
  buttonDangerBorder: "#DC2626",
  buttonDangerBackgroundHover: "#B91C1C",
  buttonDangerBackgroundActive: "#991B1B",
  buttonDangerAccent: "#FEF2F2",
  buttonDangerAccentForeground: "#DC2626",
  buttonDangerDisabledBackground: "#FECACA",
  buttonDangerDisabledForeground: "#F87171",
  // Input
  inputBackground: "transparent",
  inputForeground: "#09090B",
  inputBorder: "#E4E4E7",
  inputBorderFocus: "#18181B",
  inputRingFocus: "rgba(24, 24, 27, 0.2)",
  inputPlaceholder: "#A1A1AA",
  inputBorderError: "#DC2626",
  inputRingError: "rgba(220, 38, 38, 0.2)",
  inputDisabledBackground: "#F4F4F5",
  inputDisabledForeground: "#A1A1AA",
  // Checkbox
  checkboxBackground: "transparent",
  checkboxForeground: "transparent",
  checkboxBorder: "#D4D4D8",
  checkboxCheckedBackground: "#18181B",
  checkboxCheckedForeground: "#FFFFFF",
  checkboxCheckedBorder: "#18181B",
  checkboxDisabledBackground: "#F4F4F5",
  checkboxDisabledForeground: "#D4D4D8",
  checkboxDisabledBorder: "#E4E4E7",
  checkboxLabel: "#09090B",
  checkboxLabelDisabled: "#A1A1AA",
  // Radio
  radioBorder: "#D4D4D8",
  radioBackground: "transparent",
  radioSelectedBorder: "#18181B",
  radioSelectedDot: "#18181B",
  radioDisabledBorder: "#E4E4E7",
  radioDisabledBackground: "#F4F4F5",
  radioDisabledDot: "#D4D4D8",
  radioLabel: "#09090B",
  radioLabelDisabled: "#A1A1AA",
  // Switch
  switchTrack: "#E4E4E7",
  switchTrackActive: "#18181B",
  switchThumb: "#FFFFFF",
  switchThumbActive: "#FFFFFF",
  switchTrackDisabled: "#F4F4F5",
  switchThumbDisabled: "#D4D4D8",
  switchLabel: "#09090B",
  switchLabelDisabled: "#A1A1AA",
};
