import type {
  LetterSpacingSize,
  LineHeightSize,
  TypographyVariant,
  TypographyVariantStyle,
} from "../../types";

export const lineHeights: Record<LineHeightSize, number> = {
  xs: 16,
  sm: 18,
  md: 22,
  lg: 24,
  xl: 28,
  xxl: 32,
  xxxl: 38,
  xxxxl: 44,
  xxxxxl: 56,
};

export const letterSpacings: Record<LetterSpacingSize, number> = {
  tighter: -0.8,
  tight: -0.4,
  normal: 0,
  wide: 0.4,
  wider: 0.8,
};

export const typography: Record<TypographyVariant, TypographyVariantStyle> = {
  display1: {
    fontSize: 48,
    lineHeight: lineHeights.xxxxxl,
    fontFamily: "System",
    fontWeight: 800,
    letterSpacing: letterSpacings.tighter,
  },
  display2: {
    fontSize: 36,
    lineHeight: lineHeights.xxxxl,
    fontFamily: "System",
    fontWeight: 800,
    letterSpacing: letterSpacings.tighter,
  },
  display3: {
    fontSize: 30,
    lineHeight: lineHeights.xxxl,
    fontFamily: "System",
    fontWeight: 800,
    letterSpacing: letterSpacings.tighter,
  },
  h1: {
    fontSize: 48,
    lineHeight: lineHeights.xxxxxl,
    fontFamily: "System",
    fontWeight: 700,
    letterSpacing: letterSpacings.tighter,
  },
  h2: {
    fontSize: 36,
    lineHeight: lineHeights.xxxxl,
    fontFamily: "System",
    fontWeight: 700,
    letterSpacing: letterSpacings.tighter,
  },
  h3: {
    fontSize: 30,
    lineHeight: lineHeights.xxxl,
    fontFamily: "System",
    fontWeight: 700,
    letterSpacing: letterSpacings.tight,
  },
  h4: {
    fontSize: 24,
    lineHeight: lineHeights.xxl,
    fontFamily: "System",
    fontWeight: 600,
    letterSpacing: letterSpacings.tight,
  },
  h5: {
    fontSize: 20,
    lineHeight: lineHeights.xl,
    fontFamily: "System",
    fontWeight: 600,
    letterSpacing: letterSpacings.normal,
  },
  h6: {
    fontSize: 17,
    lineHeight: lineHeights.lg,
    fontFamily: "System",
    fontWeight: 600,
    letterSpacing: letterSpacings.normal,
  },
  subtitle1: {
    fontSize: 17,
    lineHeight: lineHeights.lg,
    fontFamily: "System",
    fontWeight: 500,
    letterSpacing: letterSpacings.normal,
  },
  subtitle2: {
    fontSize: 15,
    lineHeight: lineHeights.md,
    fontFamily: "System",
    fontWeight: 500,
    letterSpacing: letterSpacings.normal,
  },
  body1: {
    fontSize: 17,
    lineHeight: lineHeights.lg,
    fontFamily: "System",
    fontWeight: 400,
    letterSpacing: letterSpacings.normal,
  },
  body2: {
    fontSize: 15,
    lineHeight: lineHeights.md,
    fontFamily: "System",
    fontWeight: 400,
    letterSpacing: letterSpacings.normal,
  },
  body3: {
    fontSize: 13,
    lineHeight: lineHeights.sm,
    fontFamily: "System",
    fontWeight: 400,
    letterSpacing: letterSpacings.normal,
  },
  body4: {
    fontSize: 11,
    lineHeight: lineHeights.xs,
    fontFamily: "System",
    fontWeight: 400,
    letterSpacing: letterSpacings.normal,
  },
  caption1: {
    fontSize: 13,
    lineHeight: lineHeights.sm,
    fontFamily: "System",
    fontWeight: 500,
    letterSpacing: letterSpacings.wide,
  },
  caption2: {
    fontSize: 11,
    lineHeight: lineHeights.xs,
    fontFamily: "System",
    fontWeight: 500,
    letterSpacing: letterSpacings.wide,
  },
  caption3: {
    fontSize: 11,
    lineHeight: lineHeights.xs,
    fontFamily: "System",
    fontWeight: 400,
    letterSpacing: letterSpacings.wide,
  },
  label: {
    fontSize: 13,
    lineHeight: lineHeights.sm,
    fontFamily: "System",
    fontWeight: 600,
    letterSpacing: letterSpacings.wide,
  },
  button: {
    fontSize: 15,
    lineHeight: lineHeights.md,
    fontFamily: "System",
    fontWeight: 600,
    letterSpacing: letterSpacings.normal,
  },
  overline: {
    fontSize: 11,
    lineHeight: lineHeights.xs,
    fontFamily: "System",
    fontWeight: 600,
    letterSpacing: letterSpacings.wider,
  },
  code: {
    fontSize: 13,
    lineHeight: lineHeights.md,
    fontFamily: "System",
    fontWeight: 400,
    letterSpacing: letterSpacings.normal,
  },
};
